### ISSUE TITLE
Module cannot locate snowboy.node

### ISSUE THREAD

**Issue by kaisark** [dolanmiu/MMM-awesome-alexa#3]
I have been able to get AVS working on my Raspberry Pi 3 using Amazon Sample App. I thought I would give your module a try for fun.

I was able to install the MMM-awesome-alexa module and dependencies, but I run into a Magic Mirror runtime error.

"WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-linux-arm/snowboy.node'

I noticed the file actually resides under:
pi@rpi1:~/MagicMirror $ sudo ls -lart /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node
-rwxr-xr-x 1 pi pi 711044 Mar 24 21:17 /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node

Did I miss a step during the install/build?

Thanks!

**Comment by bogdanabadi** [comment]
This issue is a bit common, there are few dependencies from Snowboy. Specifically here https://github.com/Kitt-AI/snowboy#compile-a-node-addon. The second command should be done inside the node_module of the MMM-awesome-alexa directory and if the command gave you an error, precede it with `node` and then the command.

Even though this solves your error, there is a hardware limitation on the PI3 that prevents this module to function correctly at the moment. Hope next week it will be functioning properly.

**Comment by dolanmiu** [comment]
Wow, everybody has this issue

**Comment by henrikra** [comment]
I guess this was fixed with `npm run electron-rebuild` so this can be closed?

**Comment by dolanmiu** [comment]
Closing

**Comment by Bala0804** [comment]
@dolanmiu , @henrikra 
I performed the electron rebuild inside the MMM Awesome Alexa folder. And it is successful. But Still I face the same error.

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node

So I tried to Compile the Node as per this, https://github.com/Kitt-AI/snowboy#compile-a-node-addon
But still I get the above mentioned error. Please help me out.
